###

GET http://localhost:3000/customer/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ldHJhMTIzIiwiaWF0IjoxNjM5MDQyNjA3fQ.8hglEXbYBcUSmsiS7C_Tzv0GIXEvmQ3nU7-G1_mDmVo

###
POST http://localhost:3000/customers/ 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ldHJhMTIzIiwiaWF0IjoxNjM5MDQyNjA3fQ.8hglEXbYBcUSmsiS7C_Tzv0GIXEvmQ3nU7-G1_mDmVo


content
POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"netra",
    "username":"netra123",
    "password": "netra@456",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"netra123",
    "password": "netra@456"
}